redirects = [
  {from = "/public/api/*", to = "/public/api/:splat"},
  {from = "/*", to = "/", status = 200}
]

[build]
  command = "yarn build-netlify"
  publish = "apps/site/build"
  environment = { NODE_VERSION = "18.9.1", YARN_VERSION = "3.2.4" }

[dev]
  publish = "apps/site/build"
  port = 3333
